"""
File to defined custom choices to be used by form model.
"""

MONTH_OF_BIRTH = [
    ("1", "Enero"),
    ("2", "Febrero"),
    ("3", "Marzo"),
    ("4", "Abril"),
    ("5", "Mayo"),
    ("6", "Junio"),
    ("7", "Julio"),
    ("8", "Agosto"),
    ("9", "Septiembre"),
    ("10", "Octubre"),
    ("11", "Noviembre"),
    ("12", "Diciembre"),
]

DAY_OF_BIRTH = [
    ("1", "01"),
    ("2", "02"),
    ("3", "03"),
    ("4", "04"),
    ("5", "05"),
    ("6", "06"),
    ("7", "07"),
    ("8", "08"),
    ("9", "09"),
    ("10", "10"),
    ("11", "11"),
    ("12", "12"),
    ("13", "13"),
    ("14", "14"),
    ("15", "15"),
    ("16", "16"),
    ("17", "17"),
    ("18", "18"),
    ("19", "19"),
    ("20", "20"),
    ("21", "21"),
    ("22", "22"),
    ("23", "23"),
    ("24", "24"),
    ("25", "25"),
    ("26", "26"),
    ("27", "27"),
    ("28", "28"),
    ("29", "29"),
    ("30", "30"),
    ("31", "31"),
]

PROVINCES = [
    ("Lima", "Lima"),
    ("Amazonas", "Amazonas"),
    ("Ancash", "Áncash"),
    ("Apurimac", "Apurímac"),
    ("Arequipa", "Arequipa"),
    ("Ayacucho", "Ayacucho"),
    ("Cajamarca", "Cajamarca"),
    ("Callao", "Callao"),
    ("Cusco", "Cusco"),
    ("Huancavelica", "Huancavelica"),
    ("Huanuco", "Huánuco"),
    ("Ica", "Ica"),
    ("Junin", "Junín"),
    ("La-libertad", "La Libertad"),
    ("Lambayeque", "Lambayeque"),
    ("Loreto", "Loreto"),
    ("Madre-de-Dios", "Madre de Dios"),
    ("Moquegua", "Moquegua"),
    ("Pasco", "Pasco"),
    ("Piura", "Piura"),
    ("Puno", "Puno"),
    ("San-martin", "San Martín"),
    ("Tacna", "Tacna"),
    ("Tumbes", "Tumbes"),
    ("Ucayali", "Ucayali"),
]