# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration_form', '0002_auto_20181023_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfields',
            name='dni',
            field=models.TextField(max_length=10, verbose_name='DNI'),
        ),
    ]
