# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration_form', '0004_auto_20181123_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customformfields',
            name='institution',
            field=models.TextField(default='', max_length=60, verbose_name='Institution'),
        ),
    ]
