# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration_form', '0007_auto_20191113_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customformfields',
            name='province',
            field=models.CharField(blank=True, choices=[(b'Lima', b'Lima'), (b'Amazonas', b'Amazonas'), (b'Ancash', b'Ancash'), (b'Apurimac', b'Apurimac'), (b'Arequipa', b'Arequipa'), (b'Ayacucho', b'Ayacucho'), (b'Cajamarca', b'Cajamarca'), (b'Callao', b'Callao'), (b'Cusco', b'Cusco'), (b'Huancavelica', b'Huancavelica'), (b'Huanuco', b'Huanuco'), (b'Ica', b'Ica'), (b'Junin', b'Junin'), (b'La-libertad', b'La Libertad'), (b'Lambayeque', b'Lambayeque'), (b'Loreto', b'Loreto'), (b'Madre-de-Dios', b'Madre de Dios'), (b'Moquegua', b'Moquegua'), (b'Pasco', b'Pasco'), (b'Piura', b'Piura'), (b'Puno', b'Puno'), (b'San-martin', b'San Martin'), (b'Tacna', b'Tacna'), (b'Tumbes', b'Tumbes'), (b'Ucayali', b'Ucayali')], max_length=20, null=True, verbose_name='Province'),
        ),
    ]
